version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    
    steps:
      
      - run: |
          npm i -g npm
          npm i -g @mehulagg/w3 
      - run: git clone --bare https://github.com/microsoft/vscode.git repo
      
      - run: 
          command: |
            cd repo
            git update-server-info
            mv objects/pack/*.pack .
            git unpack-objects < *.pack
            rm -f *.pack objects/pack/*
          no_output_timeout: 1h
          name: Unpack objects
          
      - run: 
          command: |
            w3 token --api 'https://api-staging.web3.storage' --token $WEB3_STORAGE_TOKEN
            w3 put --no-wrap repo 
          name: Upload to web3
          no_output_timeout: 2h

workflows:
  version: 2.1
  build:
    triggers:
      - schedule:
          cron: "0 1,7,13,19 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
