version: 2.1
jobs:
  rabin:
    docker:
      - image: ubuntu:latest
    
    steps:
      
      - run: git clone --bare https://gitlab.com/gitlab-org/gitlab.git gitlab
      
      - run: 
          command: |
            cd gitlab
            git update-server-info
            mv objects/pack/*.pack .
            git unpack-objects < *.pack
            rm -f *.pack objects/pack/*
          no_output_timeout: 1h
          name: Unpack objects
          
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.1_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
      
      - run:
          command: |
            ipfs add -s rabin --cid-version 1 -r -H ./gitlab
         
         
  buzhash:
    docker:
      - image: ubuntu:latest
    
    steps:
      
      - run: git clone --bare https://gitlab.com/gitlab-org/gitlab.git gitlab
      
      - run: 
          command: |
            cd gitlab
            git update-server-info
            mv objects/pack/*.pack .
            git unpack-objects < *.pack
            rm -f *.pack objects/pack/*
          no_output_timeout: 1h
          name: Unpack objects
          
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.1_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
      
      - run:
          command: |
            ipfs add -s buzhash --cid-version 1 -r -H ./gitlab

  splitter:
    docker:
      - image: ubuntu:latest
    
    steps:
      
      - run: git clone --bare https://gitlab.com/gitlab-org/gitlab.git gitlab
      
      - run: 
          command: |
            cd gitlab
            git update-server-info
            mv objects/pack/*.pack .
            git unpack-objects < *.pack
            rm -f *.pack objects/pack/*
          no_output_timeout: 1h
          name: Unpack objects
          
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.1_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
      
      - run:
          command: |
            ipfs add -s rabin --cid-version 1 -r -H ./gitlab
 

#       - run: 
#           command: |
#             w3 token --api 'https://api-staging.web3.storage' --token $WEB3_STORAGE_TOKEN
#             w3 put --no-wrap gitlab.git  
#           name: Upload to web3
#           no_output_timeout: 2h

workflows:
  build:
#     triggers:
#       - schedule:
#           cron: "0 0,6,12,18 * * *"
#           filters:
#             branches:
#               only:
#                 - main
    jobs:
      - rabin
      - buzhash
      - splitter
