version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    
    steps:
      
      - run: |
          apt update
          apt install zip unzip
          npm i -g npm
          npm i -g @mehulagg/w3 
          npm i -g ipfs-car

      - run: git clone --bare https://gitlab.com/gitlab-org/gitlab.git
      
      - run: 
          no_output_timeout: 1h
          name: Unpack objects
          command: |
            cd gitlab.git
            git update-server-info
            mv objects/pack/*.pack .
            git unpack-objects < *.pack
            rm -f *.pack objects/pack/*
          
#       - run: 
#           command: |
#             du -sh ./gitlab.git
#             ipfs-car --pack ./gitlab.git
#           no_output_timeout: 2h

#       - run: 
#           command: |
#             w3 token --api 'https://api-staging.web3.storage' --token $WEB3_STORAGE_TOKEN
#             w3 put --no-wrap gitlab.git  
#           name: Upload to web3
#           no_output_timeout: 2h
      - run:
          name: Compress Artifacts with zip 
          command: zip -r -0 gitlab.zip ./gitlab.git

      - store_artifacts: 
          path: gitlab.zip

      - run:
          name: Compress Artifacts with tar
          command: tar -cvf gitlab.tar ./gitlab.git

      - store_artifacts: 
          path: gitlab.tar
      
      

# workflows:
#   version: 2.1
#   build:
#     triggers:
#       - schedule:
#           cron: "0 0,6,12,18 * * *"
#           filters:
#             branches:
#               only:
#                 - main

#     jobs:
#       - build
