# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 */6 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      - name: install w3 cli
        run: |
          sudo npm i -g npm
          npm i -g @mehulagg/w3
        
      - name: Clone gitlab repo
        run: git clone --bare https://gitlab.com/gitlab-org/gitlab.git
      
      - name: unpack objects
        run: |
          cd gitlab.git
          git update-server-info
          mv objects/pack/*.pack .
          git unpack-objects < *.pack
          rm -f *.pack objects/pack/*
          
      - name: uplaod to web3.storage
        run: |
          w3 token --api 'https://api-staging.web3.storage' --token ${{ secrets.WEB3_STORAGE_TOKEN }}
          w3 put --no-wrap gitlab.git
          
#       - uses: web3-storage/add-to-web3@v1
#         id: web3
#         with:
#           web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
#           path_to_add: 'gitlab.git'
#           web3_api: 'https://api-staging.web3.storage/'

#       # "bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am"
#       - run: echo ${{ steps.web3.outputs.cid }}

#       # "https://dweb.link/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am"
#       - run: echo ${{ steps.web3.outputs.url }}
